version: '3.8'

services:
  webtunnel:
    build: .
    ports:
      - "8443:8443"
    environment:
      - WEBTUNNEL_DATABASE_URL=postgres://webtunnel:password@postgres:5432/webtunnel?sslmode=disable
      - WEBTUNNEL_REDIS_URL=redis://redis:6379
      - WEBTUNNEL_AUTH_JWT_SECRET=your-super-secure-jwt-secret-change-in-production
    depends_on:
      - postgres
      - redis
    volumes:
      - ./sessions:/tmp/webtunnel/sessions
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=webtunnel
      - POSTGRES_USER=webtunnel
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # Optional: Monitoring stack
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana:/etc/grafana/provisioning
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  prometheus_data:
  grafana_data: